### ISSUE TITLE
Include GPL license text

### ISSUE THREAD

**Issue by mtasaka** [cldwalker/debugger-linecache#9]
As lib/linecache19.rb is under GPLv2+, please include GPL license text in gem so that license can be easily be parsed when packaging on distro, thank you.

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 10 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/debugger-linecache#9). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
Thanks for the suggestion but the header information in that file is enough to easily parse that it's a GPL license. If you're referring to adding license info in the gemspec I don't do that for any of my gems
